---

name: Run linter
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: almalinux:9
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install rpmlint
        run: |
          dnf install -y rpmlint

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@8ca4608ef7f4daeb54f5205b20d0b7cb42f11143  # v0.8.14
        with:
          pixi-version: v0.56.0
          cache: false
          frozen: true

      - name: Run linting checks
        run: pixi run lint
